# Generated by Django 4.2.4 on 2023-10-14 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='prent_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.productbrand', verbose_name='برند والد'),
        ),
    ]
