# Generated by Django 4.2.4 on 2023-10-14 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_rename_prent_brand_productbrand_parent_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbrand',
            name='parent_brand',
        ),
    ]
