# Generated by Django 4.2.4 on 2023-10-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_remove_productbrand_parent_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='url_title',
            field=models.CharField(db_index=True, default='url_title', max_length=100, verbose_name='عنوان در url'),
            preserve_default=False,
        ),
    ]
