# Generated by Django 4.2.7 on 2023-11-27 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سبد خرید کاربر', 'verbose_name_plural': 'سبد های خرید کاربران'},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': 'آیتم سبد خرید', 'verbose_name_plural': 'کالاهای سبد های خرید کاربران'},
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='final_product_price',
        ),
    ]
