# Generated by Django 4.2.4 on 2023-09-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main_settings', models.BooleanField(default=False, verbose_name='تنظیمات اصلی')),
                ('site_name', models.CharField(max_length=100, verbose_name='نام سایت')),
                ('site_url', models.URLField(max_length=500, verbose_name='دامنه سایت')),
                ('phone_number', models.IntegerField(verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('logo', models.ImageField(upload_to='images/site', verbose_name='لوگو سایت')),
                ('about_us', models.TextField(blank=True, null=True, verbose_name='درباره ما')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
