# Generated by Django 4.2.4 on 2023-09-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'تنظیمات', 'verbose_name_plural': 'تنظیمات'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره تماس'),
        ),
    ]
