# Generated by Django 4.2.4 on 2023-09-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_alter_sitesettings_options_sitesettings_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/site', verbose_name='لوگو سایت'),
        ),
    ]
