# Generated by Django 4.2.4 on 2023-09-12 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_alter_sitesettings_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLinkCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسته بندی لینک ها',
                'verbose_name_plural': 'دسته بندی های لینک ها',
            },
        ),
        migrations.CreateModel(
            name='FooterLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان سایت')),
                ('url', models.URLField(max_length=500, verbose_name='لینک')),
                ('footer_link_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_module.footerlinkcategories', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'لینک',
                'verbose_name_plural': 'لینک ها',
            },
        ),
    ]
