# Generated by Django 4.2.4 on 2023-10-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0005_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان بنر')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='آدرس بنر')),
                ('image', models.ImageField(upload_to='images/banners', verbose_name='تصویر')),
                ('position', models.CharField(choices=[('index_page', 'صفحه اصلی'), ('products_page', 'صفحه محصولات'), ('product_detail_page', 'صفحه جزنیات محصول'), ('articles_page', 'صفحه مقالات'), ('article_detail_page', 'صفحه مقاله'), ('contact_us_page', 'صفحه تماس باما'), ('about_us_page', 'صفحه درباره ما')], max_length=200, verbose_name='جایگاه نمایشی')),
            ],
            options={
                'verbose_name': 'بنر تبلیغاتی',
                'verbose_name_plural': 'بنر های تبلیغاتی',
            },
        ),
    ]
