# Generated by Django 4.2.4 on 2023-10-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0006_sitebanners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebanners',
            name='position',
            field=models.CharField(choices=[('index_page', 'صفحه اصلی'), ('products_page', 'صفحه محصولات'), ('product_detail_page', 'صفحه جزنیات محصول'), ('articles_page', 'صفحه مقالات'), ('article_detail_page', 'صفحه جزئیات مقاله'), ('contact_us_page', 'صفحه تماس باما'), ('about_us_page', 'صفحه درباره ما')], max_length=200, verbose_name='جایگاه نمایشی'),
        ),
        migrations.AlterField(
            model_name='sitebanners',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک بنر'),
        ),
    ]
