# Generated by Django 4.2.4 on 2023-09-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_remove_user_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نوع پیام')),
                ('text', models.CharField(max_length=500, verbose_name='متن پیام')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'اختار حساب کاربری',
                'verbose_name_plural': 'اختار های حساب کاربری',
            },
        ),
    ]
