# Generated by Django 4.2.4 on 2023-09-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0005_registermessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermessages',
            name='success_url',
            field=models.URLField(max_length=300, null=True, verbose_name='آدرس لینک'),
        ),
    ]
