# Generated by Django 4.2.4 on 2023-09-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0006_registermessages_success_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermessages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/messages', verbose_name='تصویر پیام'),
        ),
    ]
