# Generated by Django 4.2.4 on 2023-09-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0007_registermessages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermessages',
            name='url_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان لینک'),
        ),
    ]
