# Generated by Django 4.2.4 on 2023-09-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0008_registermessages_url_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermessages',
            name='success_url',
        ),
        migrations.RemoveField(
            model_name='registermessages',
            name='url_title',
        ),
    ]
