# Generated by Django 4.2.4 on 2023-09-11 05:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0009_remove_registermessages_success_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_active_code_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
