# Generated by Django 4.2.4 on 2023-09-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0010_user_email_active_code_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_user',
            field=models.TextField(blank=True, null=True, verbose_name='درباره کاربر'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/user', verbose_name='تصویر کاربر'),
        ),
    ]
