# Generated by Django 4.2.4 on 2023-09-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0011_user_about_user_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile', verbose_name='تصویر کاربر'),
        ),
    ]
