# Generated by Django 4.2.4 on 2023-09-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0012_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس کاربر'),
        ),
    ]
